{
 "title": "uki0x's VPS Overview",
 "description": "VPS总览",
 "tags": [
  "Blackbox",
  "Node",
  "VictoriaMetrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vpsname",
    "label": "选择VPS",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{job=\"node\"}))"
    }
   },
   { "name": "province", "label": "省份", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  { "title": "$vpsname Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$vpsname ICMP",
   "type": "timeseries",
   "description": "ICMP",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_icmp\", instance=~\"$vpsname\", name=~\"$province.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$vpsname Tcping",
   "type": "timeseries",
   "description": "Tcping",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "repeat": "vpsname",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\",instance=~\"$vpsname\", name=~\"$province.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$vpsname ICMP Loss",
   "type": "timeseries",
   "description": "丢包率",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "repeat": "vpsname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg_over_time(probe_success{job=\"blackbox_icmp\",instance=~\"$vpsname\", name=~\"$province.*\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$vpsname TCP Loss",
   "type": "timeseries",
   "description": "丢包率",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "repeat": "vpsname",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg_over_time(probe_success{job=\"blackbox\",instance=~\"$vpsname\", name=~\"$province.*\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$vpsname 流媒体测试",
   "type": "stat",
   "description": "流媒体测试",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "repeat": "vpsname",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "streaming_unlock_status{instance=~\"$vpsname\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}